-- ============================================================================
-- Team 1: Switch4Good Impact Tracking Database
-- DDL (Data Definition Language) - Table Creation
-- ============================================================================
-- This file contains all CREATE TABLE statements, indexes, and constraints
-- for the Switch4Good Service Learning Program tracking system.
-- ============================================================================

-- ============================================================================
-- CORE DIMENSION TABLES
-- ============================================================================

-- Schools/Universities Table
CREATE TABLE "schools" (
  "school_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "school_name" text UNIQUE NOT NULL
);

-- Semesters Table (Academic Terms)
CREATE TABLE "semesters" (
  "semester_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "season" text NOT NULL,
  "year" int NOT NULL
);

-- Staff Contacts Table (S4G Staff and Partner Contacts)
CREATE TABLE "staff_contacts" (
  "staff_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "full_name" text NOT NULL,
  "email" text,
  "role_title" text,
  "organization" text,
  "notes" text
);

-- Programs Table (Service Learning Programs)
CREATE TABLE "programs" (
  "program_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "program_name" text NOT NULL,
  "school_id" bigint,
  "website" text,
  "program_type" text,
  "season_hint" text,
  "needs_formalization" boolean,
  "notes" text
);

-- ============================================================================
-- PROGRAM ACTIVITY TRACKING
-- ============================================================================

-- Program Semester Activity (Links Programs to Semesters)
CREATE TABLE "program_semester_activity" (
  "program_id" bigint,
  "semester_id" bigint,
  "is_active" boolean,
  "most_recent_contact_date" date,
  "sg4_staff_contact_id" bigint,
  "partner_staff_contact_id" bigint,
  "partner_email" text,
  "notes" text,
  PRIMARY KEY ("program_id", "semester_id")
);

-- ============================================================================
-- STUDENT TABLES
-- ============================================================================

-- Students Table (Student Information)
CREATE TABLE "students" (
  "student_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "full_name" text NOT NULL,
  "email" text UNIQUE,
  "pronouns" text,
  "tshirt_size" text,
  "year_in_school" text,
  "areas_of_interest" text
);

-- Student Participation (Links Students to Programs per Semester)
CREATE TABLE "student_participation" (
  "participation_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "student_id" bigint,
  "program_id" bigint,
  "semester_id" bigint,
  "sg4_staff_id" bigint,
  "project_name" text,
  "project_start_date" date,
  "project_end_date" date,
  "meeting_cadence" text,
  "conflicting_datetimes" text,
  "success_metric" text,
  "created_at" timestamp
);

-- Student Checklist Items (Onboarding Tasks)
CREATE TABLE "student_checklist_item" (
  "checklist_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "participation_id" bigint,
  "item_type" text,
  "status" boolean,
  "completed_at" date,
  "notes" text
);

-- ============================================================================
-- CHECK-IN AND HOURS TRACKING
-- ============================================================================

-- Survey Check-ins
CREATE TABLE "survey_checkin" (
  "survey_checkin_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "participation_id" bigint,
  "checkin_number" int,
  "completed" boolean,
  "completed_at" date,
  "notes" text
);

-- Meeting Check-ins
CREATE TABLE "meeting_checkin" (
  "meeting_checkin_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "participation_id" bigint,
  "meeting_number" int,
  "occurred" boolean,
  "meeting_date" date,
  "notes" text
);

-- Hours Log (Weekly Hours Worked)
CREATE TABLE "hours_log" (
  "hours_log_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "participation_id" bigint,
  "period_number" int,
  "week_start_date" date,
  "hours" numeric,
  "notes" text
);

-- ============================================================================
-- DELIVERABLES TRACKING
-- ============================================================================

-- Deliverables Reference Table
CREATE TABLE "deliverables" (
  "deliverable_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "deliverable_name" text UNIQUE,
  "description" text
);

-- Deliverable Completion (Links Students to Deliverables)
CREATE TABLE "deliverable_completion" (
  "completion_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "participation_id" bigint,
  "deliverable_id" bigint,
  "completed" boolean,
  "completed_at" date,
  "notes" text
);

-- ============================================================================
-- COURSE OFFERINGS
-- ============================================================================

-- Course Offerings Table (Service Learning Courses per Semester)
CREATE TABLE "course_offerings" (
  "course_offering_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "school_id" bigint,
  "program_id" bigint,
  "semester_id" bigint,
  "sg4_staff_id" bigint,
  "faculty_staff_contact_id" bigint,
  "ty_note" text,
  "students_participating" int,
  "total_classes_in_session" int,
  "status" text,
  "notes" text,
  "next_steps" text,
  "course_details" text
);

-- ============================================================================
-- METRICS TRACKING (CAN - Touchpoints, Engagements, Conversions)
-- ============================================================================

-- CAN Metrics Table
CREATE TABLE "can_metrics" (
  "metric_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "metric_date" date,
  "is_ongoing" boolean,
  "impression" text,
  "touchpoints" int,
  "engagements" int,
  "conversions" int,
  "program_id" bigint,
  "school_id" bigint,
  "notes" text
);

-- ============================================================================
-- STAGING TABLES (For Data Import/ETL)
-- ============================================================================

-- Staging: Student Tracker Import
CREATE TABLE "stg_ss1_student_tracker" (
  "stg_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" text,
  "sg4_staff" text,
  "pronouns" text,
  "tshirt_size" text,
  "school_program" text,
  "email_address" text,
  "year_in_school" text,
  "areas_of_interest" text,
  "projects" text,
  "project_duration" text,
  "meeting_cadence" text,
  "conflicting_dates_times" text,
  "success_metric" text,
  "date_intro_email_sent" text,
  "attended_orientation" text,
  "read_community_guidelines" text,
  "signed_media_release" text,
  "sent_headshot" text,
  "completed_deliverables_raw" text,
  "survey_checkins_raw" text,
  "meeting_checkins_raw" text,
  "hours_worked_raw" text,
  "total_hours_per_student" text,
  "notes_raw" text,
  "source_file" text,
  "imported_at" timestamp
);

-- Staging: Program/Course Tab Import
CREATE TABLE "stg_ss1_program_course_tab" (
  "stg_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "school" text,
  "sg4_staff" text,
  "program" text,
  "faculty_staff" text,
  "ty_note" text,
  "students_participating" text,
  "total_classes_in_session" text,
  "status" text,
  "notes" text,
  "next_steps" text,
  "course_details" text,
  "source_file" text,
  "imported_at" timestamp
);

-- Staging: CAN Metrics Import
CREATE TABLE "stg_ss2_can_metrics" (
  "stg_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "date_raw" text,
  "impression" text,
  "touchpoints_raw" text,
  "engagements_raw" text,
  "conversions_raw" text,
  "source_file" text,
  "imported_at" timestamp
);

-- Staging: Program Directory Import
CREATE TABLE "stg_ss3_program_directory" (
  "stg_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "program" text,
  "website" text,
  "program_type" text,
  "school" text,
  "season" text,
  "semesters_active" text,
  "needs_formalization_raw" text,
  "most_recent_contact_raw" text,
  "sg4_staff_contact" text,
  "staff" text,
  "email_address" text,
  "notes" text,
  "source_file" text,
  "imported_at" timestamp
);

-- ============================================================================
-- INDEXES (Performance Optimization)
-- ============================================================================

CREATE UNIQUE INDEX ON "semesters" ("season", "year");
CREATE UNIQUE INDEX ON "programs" ("program_name", "school_id");
CREATE UNIQUE INDEX ON "student_participation" ("student_id", "program_id", "semester_id");
CREATE UNIQUE INDEX ON "student_checklist_item" ("participation_id", "item_type");
CREATE UNIQUE INDEX ON "survey_checkin" ("participation_id", "checkin_number");
CREATE UNIQUE INDEX ON "meeting_checkin" ("participation_id", "meeting_number");
CREATE UNIQUE INDEX ON "deliverable_completion" ("participation_id", "deliverable_id");

-- ============================================================================
-- FOREIGN KEY CONSTRAINTS (Referential Integrity)
-- ============================================================================

-- Programs references Schools
ALTER TABLE "programs" ADD FOREIGN KEY ("school_id") REFERENCES "schools" ("school_id");

-- Program Semester Activity references
ALTER TABLE "program_semester_activity" ADD FOREIGN KEY ("program_id") REFERENCES "programs" ("program_id");
ALTER TABLE "program_semester_activity" ADD FOREIGN KEY ("semester_id") REFERENCES "semesters" ("semester_id");
ALTER TABLE "program_semester_activity" ADD FOREIGN KEY ("sg4_staff_contact_id") REFERENCES "staff_contacts" ("staff_id");
ALTER TABLE "program_semester_activity" ADD FOREIGN KEY ("partner_staff_contact_id") REFERENCES "staff_contacts" ("staff_id");

-- Student Participation references
ALTER TABLE "student_participation" ADD FOREIGN KEY ("student_id") REFERENCES "students" ("student_id");
ALTER TABLE "student_participation" ADD FOREIGN KEY ("program_id") REFERENCES "programs" ("program_id");
ALTER TABLE "student_participation" ADD FOREIGN KEY ("semester_id") REFERENCES "semesters" ("semester_id");
ALTER TABLE "student_participation" ADD FOREIGN KEY ("sg4_staff_id") REFERENCES "staff_contacts" ("staff_id");

-- Check-in tables references
ALTER TABLE "student_checklist_item" ADD FOREIGN KEY ("participation_id") REFERENCES "student_participation" ("participation_id");
ALTER TABLE "survey_checkin" ADD FOREIGN KEY ("participation_id") REFERENCES "student_participation" ("participation_id");
ALTER TABLE "meeting_checkin" ADD FOREIGN KEY ("participation_id") REFERENCES "student_participation" ("participation_id");
ALTER TABLE "hours_log" ADD FOREIGN KEY ("participation_id") REFERENCES "student_participation" ("participation_id");

-- Deliverable references
ALTER TABLE "deliverable_completion" ADD FOREIGN KEY ("participation_id") REFERENCES "student_participation" ("participation_id");
ALTER TABLE "deliverable_completion" ADD FOREIGN KEY ("deliverable_id") REFERENCES "deliverables" ("deliverable_id");

-- Course Offerings references
ALTER TABLE "course_offerings" ADD FOREIGN KEY ("school_id") REFERENCES "schools" ("school_id");
ALTER TABLE "course_offerings" ADD FOREIGN KEY ("program_id") REFERENCES "programs" ("program_id");
ALTER TABLE "course_offerings" ADD FOREIGN KEY ("semester_id") REFERENCES "semesters" ("semester_id");
ALTER TABLE "course_offerings" ADD FOREIGN KEY ("sg4_staff_id") REFERENCES "staff_contacts" ("staff_id");
ALTER TABLE "course_offerings" ADD FOREIGN KEY ("faculty_staff_contact_id") REFERENCES "staff_contacts" ("staff_id");

-- CAN Metrics references
ALTER TABLE "can_metrics" ADD FOREIGN KEY ("program_id") REFERENCES "programs" ("program_id");
ALTER TABLE "can_metrics" ADD FOREIGN KEY ("school_id") REFERENCES "schools" ("school_id");

-- ============================================================================
-- END OF DDL FILE
-- ============================================================================
